/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bouncegame;


/*****AREA 51*****/
/**
 *
 * @author hp
 */
public class World2Page extends javax.swing.JFrame {

    /**
     * Creates new form World2Page
     */
    public World2Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\GitHub\\Fantasy-Bounce-Game\\background\\PicsArt_12-27-10.37.36.jpg")); // NOI18N

=======
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

>>>>>>> 8e71106add84574a556ef6a45abc441b1deeb334
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jButton1.setText("1");
<<<<<<< HEAD
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 70, 70));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\GitHub\\Fantasy-Bounce-Game\\background\\left-removebg-preview.png")); // NOI18N
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\GitHub\\Fantasy-Bounce-Game\\background\\PicsArt_12-27-10.37.36.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, -4, 970, 690));
=======
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 70, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\GitHub\\Fantasy-Bounce-Game\\background\\PicsArt_12-27-10.37.36.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));
>>>>>>> 8e71106add84574a556ef6a45abc441b1deeb334

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(World2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(World2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(World2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(World2Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new World2Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
<<<<<<< HEAD
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
=======
>>>>>>> 8e71106add84574a556ef6a45abc441b1deeb334
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
